# name: Github Actions 공부

# on:
#   push:
#     branches:
#       - main

# jobs:
#   only-eng:
#     runs-on: ubuntu-latest

#     steps:
#       - name: 스텝1.
#         run: echo "스텝1"

#       - name: 자체변수 사용하기
#         run: |
#           echo $GITHUB_SHA
#           echo $GITHUB_REPOSITORY

#       - name: 비밀값
#         run: |
#           echo ${{ secrets.MY_NAME }}
name: Spring REST API Test

on:
  push:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Grant execute permission to mvnw
        run: chmod +x ./mvnw

      - name: Build Spring Boot app
        run: ./mvnw clean package -DskipTests

      - name: Run Spring Boot app in background
        run: |
          nohup java -jar target/*.jar > log.txt 2>&1 &
          sleep 10

      - name: Send request to /test endpoint
        run: |
          curl -f https://word-chain-server-production.up.railway.app/test
