name: Run Tests on Push

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때마다 실행
  pull_request: # PR 시에도 실행
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest # GitHub Actions에서 사용할 운영 체제

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # 코드 체크아웃

      - name: Set up Node.js
        uses: actions/setup-node@v3 # Node.js 환경 설정
        with:
          node-version: 18 # 사용할 Node.js 버전

      - name: Install dependencies
        run: npm install # 의존성 설치

      - name: Run tests
        run: npm test # 테스트 실행
